elems:

  - src:   ^(tmux.conf)$
    dst:   ~/.<1>
    only:  f?tmux
    notes: Program xclip is needed for clipboard support

  - src:  ^(tmuxinator/.+)$
    dst:  ~/.<1>
    only: f?tmux && f?tmuxinator


# vim: set filetype=eruby.yaml :
