commands:

  - type: sync
    repo: 'https:tmux-plugins/tpm'
    dst:  '<%= get_var! :"tpm.dir" %>'
    only: f?tmux && f?tpm

elems:

  - src:   ^(tmux.conf)$
    dst:   ~/.<1>
    only:  f?tmux
    notes: Program xclip is needed for clipboard support

  - src:  ^(tmuxp/.+)$
    dst:  ~/.<1>
    only: f?tmux && f?tmuxp

  - src:  ^(tmuxinator/.+)$
    dst:  ~/.<1>
    only: f?tmux && f?tmuxinator

  - src:  ^(tmuxomatic/.+)$
    dst:  ~/.<1>
    only: f?tmux && f?tmuxomatic


# vim: set filetype=eruby.yaml :
