elems:

  - src: elems/(tmux.conf)$
    dst: ~/.<1>
    only:
      features:
        - tmux
    notes: |
      Clipboard support needs the program 'xclip'

  - src: elems/tmuxp/(.+)$
    dst: ~/.tmuxp/<1>
    only:
      features:
        - tmuxp


# vim: set filetype=eruby.yaml :
